//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csdlnc_shopee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        public string ID_DONHANG { get; set; }
        public string MASANPHAM { get; set; }
        public int SOLUONG { get; set; }
        public decimal DONGIA { get; set; }
    
        public virtual DATHANG DATHANG { get; set; }
        public virtual HANGHOA HANGHOA { get; set; }
    }
}
