//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csdlnc_shopee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONMUA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONMUA()
        {
            this.THONGTINVANCHUYENs = new HashSet<THONGTINVANCHUYEN>();
        }
    
        public string MADONVAN { get; set; }
        public string MADVVC { get; set; }
        public string ID_DONHANG { get; set; }
    
        public virtual DATHANG DATHANG { get; set; }
        public virtual DONVIVANCHUYEN DONVIVANCHUYEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGTINVANCHUYEN> THONGTINVANCHUYENs { get; set; }
    }
}
