//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csdlnc_shopee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOHANG
    {
        public string ID_NGUOIMUA { get; set; }
        public string MAHANGHOA { get; set; }
        public int SOLUONG { get; set; }
        public System.DateTime NGAYTHEM { get; set; }
    
        public virtual HANGHOA HANGHOA { get; set; }
        public virtual THANHVIEN THANHVIEN { get; set; }
    }
}
