//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csdlnc_shopee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THANHVIEN()
        {
            this.DATHANGs = new HashSet<DATHANG>();
            this.GIANHANGs = new HashSet<GIANHANG>();
            this.GIOHANGs = new HashSet<GIOHANG>();
            this.LICHSUDANHGIAGIANHANGs = new HashSet<LICHSUDANHGIAGIANHANG>();
            this.LICHSUDANHGIAHANGHOAs = new HashSet<LICHSUDANHGIAHANGHOA>();
            this.LICHSUXEMHANGHOAs = new HashSet<LICHSUXEMHANGHOA>();
            this.TAIKHOANDANGNHAPs = new HashSet<TAIKHOANDANGNHAP>();
            this.VOUCHER_NGUOIDUNG = new HashSet<VOUCHER_NGUOIDUNG>();
            this.GIANHANGs1 = new HashSet<GIANHANG>();
        }
    
        public string ID_THANHVIEN { get; set; }
        public string EMAIL_TV { get; set; }
        public int DIENTHOAI_TV { get; set; }
        public string DIACHI_TV { get; set; }
        public int NGUOIBANFLAG { get; set; }
        public int NGUOIMUAFLAG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATHANG> DATHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIANHANG> GIANHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHSUDANHGIAGIANHANG> LICHSUDANHGIAGIANHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHSUDANHGIAHANGHOA> LICHSUDANHGIAHANGHOAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHSUXEMHANGHOA> LICHSUXEMHANGHOAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAIKHOANDANGNHAP> TAIKHOANDANGNHAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VOUCHER_NGUOIDUNG> VOUCHER_NGUOIDUNG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIANHANG> GIANHANGs1 { get; set; }
    }
}
