//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csdlnc_shopee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHTOAN
    {
        public string SO_THANHTOAN { get; set; }
        public System.DateTime NGAYTHANHTOAN { get; set; }
        public string ID_DONHANG { get; set; }
        public decimal SOTIENTT { get; set; }
        public string UUDAI { get; set; }
        public string LOAITHANHTOAN { get; set; }
        public Nullable<decimal> HOANTIEN { get; set; }
        public string LOAITTONLINE { get; set; }
    
        public virtual DATHANG DATHANG { get; set; }
        public virtual VOUCHER VOUCHER { get; set; }
    }
}
