//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csdlnc_shopee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOUCHER_NGUOIDUNG
    {
        public string MAVOUCHER { get; set; }
        public string ID_NGUOIMUA { get; set; }
        public Nullable<int> TRANGTHAIDUNG { get; set; }
    
        public virtual THANHVIEN THANHVIEN { get; set; }
        public virtual VOUCHER VOUCHER { get; set; }
    }
}
